### PR TITLE
Added a way to read local json located in the assets folder with file…

### PR DESCRIPTION
**Pull request by J6ey**
… name in place of a web url.

Some people might prefer to store the json file locally. I added a check that takes the url input as the file name located in the assets folder, given it's not a web url.

### CODE REVIEW

**Comment by mikemee** [comment]
@J6ey Hi - thanks for this contribution. I'm a little confused though. How does reading a local JSON file help an older app notify the user of a new version?  I.e. the scenario that Siren is built to solve is, for example:

 * user installs version 1.5
 * developer releases version 1.6 and updates server with new JSON file
 * installed 1.5 version checks the server, reads the new JSON files and prompts the user to update

If the JSON file is local to the version 1.5 app, then it will never know about the new version that was released, so I'm a bit confused about what purpose this PR will serve?

Apologies if I'm missing something obvious!

**Comment by J6ey** [comment]
@mikemee You're completely right about that. It's probably not practical and doesn't serve much purpose other than the lack of server or the convenience of triggering Siren without making any web calls. 

In my case I just needed a temporary solution before I get the chance to add the API to the server. But either this or getting the version from the app store will do just fine. Thanks for making this library by the way!

**Comment by J6ey** [comment]
@mikemee Hi again. I still can't get my head wrapped around the purpose of a backend json just to check the version in the first place.
You don't find it strange how you need an alternative api to check this when the latest version is listed in the Play store?

**Comment by mikemee** [comment]
> You don't find it strange how you need an alternative api to check this when the latest version is listed in the Play store?

@J6ey There's no easy way to get the latest version listed in the Play store. Various libraries have tried this, with mixed success. I decided to keep it simple. See my section https://github.com/eggheadgames/Siren#similar-android-libraries - maybe one of those will have this and will work better for you.

Closing this for now. Thanks!

**Pull request closed without merging**
