### PR TITLE
New Feature HTTP Header, Custom Message from server added

### PR DESCRIPTION
**Pull request by ankitguptag18**
Developers can send the HTTP Headers to be added as a parameter to checkVersion

### CODE REVIEW

**Review by mikemee — CHANGES_REQUESTED** [review]
Thanks for this proposed contribution. 

Can you propose this change in a way that is non-breaking for existing users of the API? Eg an optional parameter or a builder. 

Can you please add updates to the readme, including a typical use case?

Thanks!

**Review by mikemee — COMMENTED** [review]
This is an interesting use case. I wonder if there’s a way to satisfy it without requiring special programming on the server (ie to read the headers and interpret and build a custom response, as this seems to suggest).

**Comment by ankitguptag18** [comment]
This is just one use case, I believe developers who would use this would already have some server-side code for their other APIs

**Comment by ankitguptag18** [comment]
If you have a paid app and a free app as different product flavours with same code base. You can pass the application name as a header and backend server will send return correct response for that app.

**Comment by ankitguptag18** [comment]
Hi Mike, 

Just wanted an update if my code is worthy of the merge.  :)

I am also working on a new feature. An optional custom message from the server in response. 

Use case:
 
We may want to give in a custom message for planned force update so that user have enough time to upgrade the app on home/office Wifi network and can save on the mobile data usage.

Better than being surprised that app is no longer usable until the upgrade. :)

Message example : 

"We will stop the support for this app version in 10 Days, Please upgrade to latest version for uninterrupted usage."

**Comment by ankitguptag18** [comment]
Hi,

I have added a new feature where we can display a custom message from the server. I have also updated the Readme with a use-case. Looking forward for the approval.

**Comment by mikemee** [comment]
Hi @ankitguptag18, sorry I haven't had time to think about this properly until now.  But I have given it more thought, and it still worries me that the proposed approach requires more than just a dumb server. 

Alternatively, what if the app modified the URL being called, based on the various details?  E.g. instead of adding HTTP headers based on version, it could instead do something like:

```java
if (MIN_API_VERSION <= 12) { 
    String SIREN_JSON_DOCUMENT_URL = "https://example.com/com.mycompany.myapp/api12/version.json"
} else {
    String SIREN_JSON_DOCUMENT_URL = "https://example.com/com.mycompany.myapp/default/version.json"
}
```
The code change is quite small and isolated to the app, and then the server can continue to be just a document server with no smarts.

What do you think?

**Comment by ankitguptag18** [comment]
Hi @mikemee, While we can do that, but that would limit the usage of this library only to the dumb servers. The changed I have proposed is optional and not mandatory. This will open doors to intelligent serves and RESTful and SOAP web service which maintain all this information in Database.

**Comment by mikemee** [comment]
> This will open doors to intelligent serves and RESTful and SOAP web service which maintain all this information in Database.

An intelligent server with a database can still _look_ like a dumb server. I.e. "What URL was asked for?  Oh, then respond with this JSON."

The difference is that it keeps the complexity lower on the device. A simple library is an easier library to use. I worry that adding extra parameters etc., both: a) makes it harder to understand (even though it is optional), and b) requires server work.

I.e. if we already have one way to do this, what is the advantage of doing it another more complicated way?

But perhaps I'm missing something else?

**Comment by ankitguptag18** [comment]
The reason I coded this, 

Reason 1:
We wanted to give a different response to the different app version. There are 2 ways of doing this. 
  (a) Have different `SIREN_JSON_DOCUMENT_URL` for every release.
  (b) Have the same `SIREN_JSON_DOCUMENT_URL` but let the server decide which response to give to which version. 

Option (a) requires that every time there is an app release a request has to be made to backend team to create a new API, In case if the developers forgot to communicate, then we may end up with multiple apps having the same API and we lose the flexibility. This option required manual code change for every release both on app side and server side, hence prone to human error. 

While in Option (b) we have to just code it once and the app will automatically send the correct headers for every release, On the server side, we can handle if there is no data for the version sent by the app send a default response, as you have mentioned. Hence no human intervention required unless needed. 

Reason 2:
We have observed over the past, once an app is gone on the market it's gone. You cannot do anything about it. It's better to have a control over server-end than making a new release. Making a new release will effect from that version onwards while having a control server side would also be applicable to the past release as well having the feature.

Reason 3:
We prefer that the update policy be 6 months. Instead of giving a sudden force update, We would prefer to push the user to latest version gradually. First, display them an Optional message and after 6 Months force them. 

Display an optional message for the previous builds within 6 Months of the release.
>Dear user, You are using an outdated version of the App. Please update the App from Google Play to enjoy new and exciting features. This version will stop working soon

Display a force message for previous builds beyond 6 Months of the release.
>Dear user, thank you for choosing the company.com App. We noticed that you are currently using an outdated version of our app, please update to the latest version of company.com to enjoy a plethora of new features.

Reason 4:

Having all this flexibility on the server side we can target a specific message for any app version with any API level.

Hope these are good enough reason :)

**Comment by ankitguptag18** [comment]
Hi Mikemee, Hope you had a chance to look at my comment.

**Comment by mikemee** [comment]
Hi, many apologies for the delay here. I'll make a decision so we can all move forward. 

I'm sorry but I'm not convinced this can't be done in the URL.  Although I'm not claiming to be an HTTP master, I've worked with it a bit, and I've seen few instances of using extra parameters in the headers vs just using the URL. 

You can handle this multiple ways, either by putting the app version / build number / whatever either as part of the URI path or as a `?version=1.42` appended to the path. The app doesn't have to be modified each time, and the server can still be modified to do something special for a specific version or build range, or it can just default to something else if not. (Either that, or I'm completely misunderstanding the scenario, but I don't think so).

So, in the name of keeping this simple, and also keeping it compatible with the iOS Siren version, I'm going to decline the part of this PR that adds the HTTP headers. I'm sorry it's taken me so long to get to this decision.

The second part about having an optional server message is something I would approve and include as a separate request. I think it's a compelling use case that I've also had in the past.

So, obviously you're free to fork and go with a separate version. No hard feelings if you do that, of course.  If you'd like to separate out the Custom Message part as a new PR, I promise to process that more promptly than this one, which unfortunately fell over a holiday period here for me.

Thanks again for ideas, the PR itself and this thoughtful discussion!

**Comment by ankitguptag18** [comment]
Thanks for the response. I will send you a separate request for only the custom message in few days. Just wanted to contribute whatever I can to the community :)

**Comment by mikemee** [comment]
@ankitguptag18 Thanks for understanding, and I look forward to that request.

Note: Please use <comma><space> between parameters in function calls. That will better match the current coding style.

**Pull request closed without merging**
